import pygame


pygame.joystick.init()
joysticks = [pygame.joystick.Joystick(x) for x in range(pygame.joystick.get_count())]

# The following event types will be generated by the joysticks
#
# JOYAXISMOTION JOYBALLMOTION JOYBUTTONDOWN JOYBUTTONUP JOYHATMOTION

# for e in pygame.event.get():  # iterate over event stack
#     print 'event : ' + str(e.type)
#     if e.type == pygame.locals.JOYAXISMOTION:  # 7
#         x, y = j.get_axis(0), j.get_axis(1)
#         print 'x and y : ' + str(x) + ' , ' + str(y)
#     elif e.type == pygame.locals.JOYBALLMOTION:  # 8
#         print 'ball motion'
#     elif e.type == pygame.locals.JOYHATMOTION:  # 9
#         print 'hat motion'
#     elif e.type == pygame.locals.JOYBUTTONDOWN:  # 10
#         print 'button down'
#     elif e.type == pygame.locals.JOYBUTTONUP:  # 11
#         print 'button up'